/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio8;

import java.text.ParseException;
import java.util.Date;

public class App {
    
    public static void main(String[] args) throws ParseException {
        Data novaData = new Data("21/08/2016");
        System.out.println("Situação da data: "+ novaData.Compara(novaData.getData()));
        System.out.println("Data: " + novaData.getData());
        
        System.out.println("Dia: " + novaData.getDia());
        System.out.println("Mês: " + novaData.getMes());
        System.out.println("Mês por extenso: " + novaData.getMesExtenso());
        System.out.println("Ano: " + novaData.getAno());
        System.out.println("É bissexto? " + novaData.isBissexto());
    }
}
